### PR TITLE
CLM-27258: Updated the latest version of JenkinsCI 2.414.1 to be tested with Java 17

### PR DESCRIPTION
**Pull request by leob-morean**
JenkinsCI version 2.414.1

Ref: CLM-27258

Jenkins https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-27258/
Jira https://sonatype.atlassian.net/browse/CLM-27258

This PR replaces https://github.com/jenkinsci/nexus-platform-plugin/pull/281

### CODE REVIEW

**Comment by koraytugay** [comment]
Please add a link to Jira and Jenkins in the Description similar to: https://github.com/jenkinsci/nexus-platform-plugin/pull/257

**Comment by leob-morean** [comment]
I modified this to draft until I complete some testing

**Comment by leob-morean** [comment]
> 

Added the links, but I won't change the branch name for this first PR. I'll follow up that rule from next one, I hope that's ok. These branches are deleted anyways.

**Comment by leob-morean** [comment]
Please let's squash before merge! :-)

**Comment by leob-morean** [comment]
Green build https://jenkins.ci.sonatype.dev/job/integrations/job/jenkins/job/feature-snapshots/job/CLM-27258/5/

**Review by eduard-tita — APPROVED** [review]
+1 And thanks for not giving up! :smile:

**Pull request merged**
