### PR TITLE
Update nexus-platform-api 3.34 to support Java 16

### PR DESCRIPTION
**Pull request by guillermo-varela**
Jira: https://issues.sonatype.org/browse/CLM-18176
Update nexus-platform-api to version 3.34 so the Jenkins plugin supports scanning Java 16 binaries.

Testing locally, the Jenkins plugin processes correctly the binaries.
Screen Shot 2021-04-19 at 12 23 33 PM

- [x] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your master branch!
- [x] Ensure that the pull request title represents the desired changelog entry
- [x] Please describe what you did
- [x] Link to relevant issues in GitHub or Jira
- [x] Link to relevant pull requests, esp. upstream and downstream changes
- [x] Ensure you have provided tests - that demonstrates feature works or fixes the issue

### CODE REVIEW

**Comment by mr-zepol** [comment]
Are the jenkins job errors related to the update?

**Comment by guillermo-varela** [comment]
> +1 Looks like this is basically just inline with existing tests that it finds additional files? Is there anyway to actually assert it found J16 stuff?

I couldn't found previous tests made for previous updates to support newer Java versions. For Java 13 and 14-15 the commits just contained the version bump:
https://github.com/jenkinsci/nexus-platform-plugin/commit/15c0353dea90a9c63b717f4ef9ea01989d7b5777#diff-600376dffeb79835ede4a0b285078036

https://github.com/jenkinsci/nexus-platform-plugin/commit/43c3f3b4b3ed5fce0f90de84f2e6b9013107e0ce

Also, I see the tests are using mocks for IQ classes so I wouldn't know how to add tests for scanning this bytecode.

There are tests in the library doing the actual hashing: https://github.com/sonatype/insight-scanner-hashing/blob/master/insight-scanner-hashing/src/test/java/com/sonatype/insight/scan/hash/JavaDigesterTest.java#L403

**Comment by guillermo-varela** [comment]
> Are the jenkins job errors related to the update?

Failures are the Jenkins instance at https://ci.jenkins.io and according to our internal docs:
> There is a Jenkins job at https://ci.jenkins.io associated to the repository, but due to our integrations tests spinning up some threads to do work that might cause errors. So for testing rely in our internal Jenkins job.

Our internal Jenkins job went fine.

**Review by jflinchbaugh — APPROVED** [review]
+1

**Review by mealingr — APPROVED** [review]
+1

**Pull request merged**
